### ISSUE TITLE
Define illustrations for use on pages

### ISSUE THREAD

**Issue by MrSunshyne** [mscraftsman/devcon2020#11]

**Comment by MrSunshyne** [comment]
There was a meeting on the 23rd January at the MSCC Office, Emmy is helping with some of the illustrations which will be comic themed and mostly black & white.

Waiting for feedback from her to continue on this

**Comment by MrSunshyne** [comment]
There was a meeting on the 23rd January at the MSCC Office, Emmy is helping with some of the illustrations which will be comic themed and mostly black & white.

Waiting for feedback from her to continue on this

**Comment by cedpoilly** [comment]
Status?

**Comment by MrSunshyne** [comment]
dis gonna be FFA !
