### ISSUE TITLE
Setup tailwind to use color scheme and fonts

### ISSUE THREAD

**Issue by MrSunshyne** [mscraftsman/devcon2020#12]
A very nice tool to generate color palettes for tailwindcss: https://javisperez.github.io/tailwindcolorshades/#/

**Comment by Saamiyah** [comment]
Hello, I'm working on this issue. Thanks.

**Comment by MrSunshyne** [comment]
@Saamiyah okay

**Comment by cedpoilly** [comment]
Closing as PR merged.
