### ISSUE TITLE
Setup production deployment pipelines

### ISSUE THREAD

**Issue by MrSunshyne** [mscraftsman/devcon2020#15]
Configure a service to deploy a new version of the website based on the following rules :

- a new push to the branch `deploy`
- the pipeline should run `npm run build` on the repo (this will output the build in the `docs` folder
- the `docs` folder is the one that should be served to the public.

Let us know where to check the pipeline status so that we can intervene if a build fails!

**Comment by Jheengut** [comment]
status?

**Comment by MrSunshyne** [comment]
@Jheengut this is done! 

thanks @jochenkirstaetter
