### ISSUE TITLE
Styling Sponsors

### ISSUE THREAD

**Issue by cedpoilly** [mscraftsman/devcon2020#23]
# Styling Sponsors

Tasks:
- [x] define the design
- [x] update the styling in the code

**Comment by nirvanpagooah** [comment]
@cedpoilly Kindly vet the design over here: https://www.figma.com/file/Osinp4D4c3AicwwpYVGlNA/Developers-Conference-2020-Website-Components?node-id=9%3A236

**Comment by nirvanpagooah** [comment]
@cedpoilly Please pull and verify the branch `sponsors-home`. 

I'll finish the responsive tomorrow.

**Comment by cedpoilly** [comment]
**Question**: Can we find a solution to make the text "BACKED BY SOME BIG PLAYERS OF THE INDUSTRY" more readable?

![image](https://user-images.githubusercontent.com/11003819/74404037-cbaad500-4e42-11ea-8960-2faa5b246258.png)

**Comment by cedpoilly** [comment]
It's okay to remove the "white to  default on hover". \
We can abide the the grayscale layer suggested in the design.

Also kindly remove the `#888` background. ✌🏼

![image](https://user-images.githubusercontent.com/11003819/74404242-54297580-4e43-11ea-8937-a7c18edd09ca.png)

**Comment by cedpoilly** [comment]
@nirvanpagooah Please find some feedback above.

**Comment by nirvanpagooah** [comment]
> **Question**: Can we find a solution to make the text "BACKED BY SOME BIG PLAYERS OF THE INDUSTRY" more readable?
> 
> ![image](https://user-images.githubusercontent.com/11003819/74404037-cbaad500-4e42-11ea-8960-2faa5b246258.png)

Hm, there is a font missing. Will see to this.

**Comment by nirvanpagooah** [comment]
> It's okay to remove the "white to default on hover".
> We can abide the the grayscale layer suggested in the design.
> 
> Also kindly remove the `#888` background. ✌🏼
> 
> ![image](https://user-images.githubusercontent.com/11003819/74404242-54297580-4e43-11ea-8937-a7c18edd09ca.png)

Will do.

**Comment by cedpoilly** [comment]
I think the font is not available on the site. Is it possible to use one which is already available in the codebase?

![image](https://user-images.githubusercontent.com/11003819/74600370-18441980-50aa-11ea-8866-99fd439c514b.png)
