### ISSUE TITLE
Artwork of Super Heroes

### ISSUE THREAD

**Issue by MrSunshyne** [mscraftsman/devcon2020#25]
Would be nice to have lightweight comic style super heroes that we can use throughout the site ! 

kindly put the files in `/public/images/heroes/<here>`

comment here about the list of super heroes

**Comment by Saamiyah** [comment]
Hi I'm working on this.

**Comment by MrSunshyne** [comment]
some of the artworks are already being used! looking great @Saamiyah  !

We have to update the Credits page accordingly to reference the authors/websites for some of these artworks in #29
