### ISSUE TITLE
[Suggestion] [UX] Scroll Snap update: `mandatory` to `proximity`

### ISSUE THREAD

**Issue by cedpoilly** [mscraftsman/devcon2020#32]
**Suggestion for UX update: Change the Home Page scroll behaviour for Scroll Snapping.**

File: `/src/assets/global.css`

Changes:
```
l.2 --  scroll-snap-type: y mandatory;
l.2 ++  scroll-snap-type: y proximity;
```

Other suggestions on the topic are most welcome.

**Comment by MrSunshyne** [comment]
good first issue indeed !

**Comment by YourFavouriteOreo** [comment]
Can we mark this as completed @cedpoilly ?

**Comment by cedpoilly** [comment]
Much better! ✌🏼
