### ISSUE TITLE
Button style ?

### ISSUE THREAD

**Issue by MrSunshyne** [mscraftsman/devcon2020#38]
Right now we have this button on the homepage (the black one in the image below).

![Screenshot 2020-02-13 at 10 05 00](https://user-images.githubusercontent.com/1721611/74406156-4e825e80-4e48-11ea-94c1-72a24877189b.jpg)

We can universally agree it's uninspired. 

Suggestions for buttons we can use around the website please?

**Comment by YourFavouriteOreo** [comment]
I'll take this one

**Comment by YourFavouriteOreo** [comment]
![Register Button](https://user-images.githubusercontent.com/10431292/74511943-97a5e180-4f20-11ea-8a2f-a49f959f03a4.png)

That's what my attempt looks like.

**Comment by MrSunshyne** [comment]
matches the theme! but i think it needs to be a little less flashy, incase we have multiple of these next to each other, it'll be way too much on the eyes. Looks very similar to the design nirvan made in the `features/sponsors-home` branch btw. T

ake a look at the implementation maybe? I can see some potential collaboration there. Cheers

**Comment by YourFavouriteOreo** [comment]
Hmmm I'll try working it around a bit. I could probsdbly achieve it using clip path and removing some of the extra atmosphere in the background at the back.

**Comment by Nythiennzo** [comment]
What do you think of this one?
![image](https://user-images.githubusercontent.com/16918311/75085431-99842c00-5542-11ea-8012-3b4367710a4b.png)

**Comment by MrSunshyne** [comment]
i like this one

**Comment by MrSunshyne** [comment]
implemented something similar on production! thanks for the inspiration @Nythiennzo
