### ISSUE TITLE
Define components for each route

### ISSUE THREAD

**Issue by MrSunshyne** [mscraftsman/devcon2020#4]
Every page/route will have it's own set of components. 

I'm guessing we can list them all here and treat each of them as separate github issues?

**Comment by cedpoilly** [comment]
> I'm guessing we can list them all here and treat each of them as separate github issues?

I agree.

**Comment by MrSunshyne** [comment]
We had a discussion about this on the 23rd Jan 2020.

The brainstorming session happened on figma. You may see it here: https://www.figma.com/file/UOIp9ymHhH5wZSghl60CPh/Le-DevCon-plan?node-id=0%3A1

**Comment by cedpoilly** [comment]
Status?

**Comment by MrSunshyne** [comment]
i feel like this one will be "in progress" till the end of times. closing because 

> something that is permanent can be considered as background noise ~ Elon Trump
