### ISSUE TITLE
Tabs vs Space For Indentations

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [mscraftsman/devcon2020#42]
In some files i see tabs used for indentations and in others space. I guess tabs better as it counts as only one char.

**Comment by cedpoilly** [comment]
Kindly check which is more present in the repo: tabs or spaces.
Spaces are generally more common, at least wrt front-end projects. ✌🏼

**Comment by rrikesh** [comment]
Since there's a `.vscode/settings.json`, you could define what to use (Personally I prefer spaces) througout the project:

``` 
{
    "editor.insertSpaces": true,
    "editor.tabSize": 4
}
```

VS Code also allows you to define indentation for different languages -- https://code.visualstudio.com/docs/getstarted/settings#_language-specific-editor-settings

**Comment by MrSunshyne** [comment]
prefer tabs. but dont care

**Comment by MrSunshyne** [comment]
closing for now as this is not essential at the moment :P 

we'll surely discuss it during the conf though

**Comment by Abdur-rahmaanJ** [comment]
Ok 🍃👍
