### ISSUE TITLE
Generic page styling

### ISSUE THREAD

**Issue by MrSunshyne** [mscraftsman/devcon2020#44]
We'll need a proper style for the generic pages. 

Something that suits the theme but not too over the top, and with the possibility of adapting to mobile screens. 

I wish I had a design to attach the this issue, but i'll leave it open to your imagination. 

As reference, use the 'extras' page. 

Basic styles needed for :

- Headings
- Paragraphs
- Links
- Icons
- Subheadings

The usual stuff. 

The page is kind ugly right now : 

![Screenshot 2020-02-14 at 12 40 08](https://user-images.githubusercontent.com/1721611/74515009-23bb0780-4f27-11ea-926b-5995952819a8.jpg)

**Comment by Abdur-rahmaanJ** [comment]
And image, we'd like to add our logo!

**Comment by MrSunshyne** [comment]
this is done. styles are in the App.vue under the class `.generic-page`
