### ISSUE TITLE
Connect Sessionize

### ISSUE THREAD

**Issue by MrSunshyne** [mscraftsman/devcon2020#5]
The schedule page should pull data from the sessionize api endpoint.

**Comment by cedpoilly** [comment]
WIP

**Comment by cedpoilly** [comment]
Connected. Temporarily pointing to 2019 endpoint, for development purposes.
A new PR will be created once the sessions for 2020 are available.

**Comment by MrSunshyne** [comment]
> A new PR will be created once the sessions for 2020 are available.

@cedpoilly Yep !
