### ISSUE TITLE
Name of Partnership Tiers

### ISSUE THREAD

**Issue by MarineNg** [mscraftsman/devcon2020#60]
JoKi would like the name of the tiers to be the Stones (Power, Space etc...) instead of diamond, titanium etc...
@cedpoilly

**Comment by MarineNg** [comment]
Diamond -> Power Stone
Titanium -> Space Stone
Platinum -> Reality Stone
Gold -> Soul Stone
Silver -> Time Stone
Bronze -> Mind Stone

**Comment by cedpoilly** [comment]
@MarineNg @jochenkirstaetter 
Kindly check this branch for updates: https://landing-sponsor--devcon2020.netlify.com/

**Comment by MrSunshyne** [comment]
looks like this is done. closing
