### ISSUE TITLE
Sponsors Landing: links in footer 

### ISSUE THREAD

**Issue by cedpoilly** [mscraftsman/devcon2020#63]
Enable the following in the footer for this version:
- Code of Conduct 
- Press Materials

**Comment by cedpoilly** [comment]
@jochenkirstaetter @MrSunshyne see PR for info #64

**Comment by MrSunshyne** [comment]
@cedpoilly just deployed a version with CoC and Press in the footer. 

Both pages have been themed as well. Kinda.

I ditched the arc building in the footer for now. sorry. responsive is a PITA with this one.
