### ISSUE TITLE
Connect Stats spreadsheet

### ISSUE THREAD

**Issue by MrSunshyne** [mscraftsman/devcon2020#7]
what the title says

**Comment by cedpoilly** [comment]
So I create a spreadsheet for now? Or do we have a one already?

**Comment by YourFavouriteOreo** [comment]
Just cautionary mention here. Google is revamping their spreadsheet API so make sure to shift to V4 although it will disable features. Migration guide available here : https://developers.google.com/sheets/api/guides/migration

**Comment by MrSunshyne** [comment]
@cedpoilly We don't have one. Go ahead a create one (or duplicate last year's)

**Comment by cedpoilly** [comment]
WIP

**Comment by cedpoilly** [comment]
Connected.
