### ISSUE TITLE
About renaming "extras" to "community" or have a separate "community" section

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [mscraftsman/devcon2020#77]
We had a discussion at Code&Coffee today about the extras page. The word does not reflect the page content, The extras section was used if i am not mistaken to list some fun activities at the begining.

**Comment by jochenkirstaetter** [comment]
Hi,

after internal discussion and due to the amount of content it shall be in favour to separate pages / sections:

- Communities
- Extra Activities

Best regards, JoKi

**Comment by MrSunshyne** [comment]
oh, was about to suggest this.

**Comment by MrSunshyne** [comment]
done!

**Comment by MrSunshyne** [comment]
https://devcon2020.netlify.com/extras
https://devcon2020.netlify.com/communities

visually, still needs some love though..
