### ISSUE TITLE
Landing page's "Developers Conference 2020" wording goes out of background circle boundary

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [mscraftsman/devcon2020#78]
![devconletters](https://user-images.githubusercontent.com/22630684/75896777-01931600-5e51-11ea-9f86-72cc4c51ad38.png)

On mobile it is well into the circle

**Comment by jochenkirstaetter** [comment]
Thanks,

IMHO, it's a duplicate of #39 
Work in progress.

Cheers, JoKi

**Comment by jochenkirstaetter** [comment]
And not really a priority issue (at the moment).
