### ISSUE TITLE
Missing package.json on https://conference.mscc.mu/

### ISSUE THREAD

**Issue by gdsmith** [mscraftsman/devcon2020#85]
I followed the link from the Meetup newsletter to the website but the site doesn't seem to be working for me. Im Getting a 404 for the following file on https://conference.mscc.mu/ https://raw.githubusercontent.com/mscraftsman/devcon2020/master/web/app/package.json and I see that file is not in source control either.

**Comment by MrSunshyne** [comment]
hi @gdsmith, package json is here: 
[https://raw.githubusercontent.com/mscraftsman/devcon2020/master/package.json](https://raw.githubusercontent.com/mscraftsman/devcon2020/master/package.json)

Where did you find that other link with web/app ? that was the structure of last year's website from what I remember.

The website seems to be working fine from here. Maybe you caught it in the middle of an azure pipeline deploy thing?

Thanks for reporting these issues!  much appreciated

**Comment by jochenkirstaetter** [comment]
Hi @gdsmith 

The conference website shows the generated output from the `docs` folder that is created and updated by the `npm run build` statement.

I'm kind of curious about why the website shall have a `package.json` file in its root folder?

As for the website, it seems to show an HTTP 403 which might be caused by a broken pipeline.
Thanks for raising the issue (indirectly).

Cheers, JoKi

**Comment by jochenkirstaetter** [comment]
Hi @gdsmith 

Oh, I see... You went into `master` branch which isn't the one that is currently deployed. That was the previous landing page.

Right now, it's the branch `landing-sponsor` that is deployed. However we already discussed internally to do some house-keeping and to shift branches. So, given a little time, `landing-sponsor` will be merged into `master` and we all shall be good and the repository shall behave as expected.

Still my Q remains why there should a package.json in the root folder of the production version of the website? Seems a security issue for me.

Cheers, JoKi

**Comment by gdsmith** [comment]
I'm not sure how your deployment is working, but this is what I see right now:

![image](https://user-images.githubusercontent.com/908695/76180674-0ac90d80-61d8-11ea-8691-999e08abc622.png)

Oddly, I get the new version of the site on my mobile, and if I visit e.g. https://conference.mscc.mu/sessions/ on my desktop I see the new site, but right now I only see the old site, so I think you might rather have a caching/cdn issue for people who previously visited the old site.

I only mention having the file in source control as the 404 I was getting is from a github url to present that file from your source control, I then _wrongly_ assumed that may have been the reason the site was not showing different content.

**Comment by MrSunshyne** [comment]
@gdsmith i think the landing page had a service-worker-type cache that saved a copy of the site in your browser. It may even be accessible without internet with this type of cache.
I should have disabled the `sw` on the landing page. My bad. 

For now you can navigate within the ` Chrome DevTools > Application > Clear Site Data `
and your issue should be resolved. 

Thanks for taking the time to report this bug in detail

**Comment by gdsmith** [comment]
Okay, yes, clearing site data has fixed the issue.
